name: Pr Issue Link Checker

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]

permissions:
  contents: read

jobs:
  pr-open-check:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Verify Linked Issue
        uses: hattan/verify-linked-issue-action@v1.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: 'Please add any related issue link in this pr'

      - name: Check on failures
        if: ${{ failure() }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 'need revision'

